Boards page
diXrom/project-management pull request #14
Opened 2022-11-12 17:13 UTC by malinna13

Main route 

- Displays all created boards as a list.

- Boards are displayed with a small preview of the available information (title, description, etc.). By clicking on the element, the user redirects to the board item (Board route). There should be a button to remove the board.

- When a user tries to delete the board, he/she should receive a confirmation modal to verify if the user wants to delete the board (to avoid deleting the board by mistake). The confirmation modal should be a generic component (one for the application).

NOT DONE : Example of extra functionality (optional): global search. Search for a task by task number, name, users assigned to it, and by the text of the task description.

2022-11-12 19:11 UTC, diXrom commented on src/shared/components/Card/index.tsx
> +      'p-6 shadow-md rounded-lg bg-white overflow-hidden transition duration-300'
Не мутируй общий компонент, ты же можешь передать в него этот класс чрз пропc className как делала в MainPage:
`<Card className="flex justify-between cursor-pointer hover:shadow-lg">
 </Card>`

2022-11-13 11:13 UTC, diXrom requested changes

2022-11-13 11:15 UTC, diXrom reviewed
Добавил замечания

2022-11-13 11:33 UTC, malinna13 commented on src/widgets/Header/ui/UserPanel.tsx
> +        <form onSubmit={handleSubmit} className="flex flex-col gap-3">
В будущем надо добавить выбор юзеров в этой форме

2022-11-13 11:33 UTC, malinna13 commented on src/widgets/Header/ui/UserPanel.tsx
> +    await addBoard({ title: inputValue, owner: user!._id, users: ['Inna'] });
это хардкодные тестовые данные, потом доделаю выбор юзеров

2022-11-13 12:04 UTC, diXrom commented on src/widgets/Header/ui/UserPanel.tsx
> +        <form onSubmit={handleSubmit} className="flex flex-col gap-3">
Понял

2022-11-13 12:40 UTC, malinna13 commented on src/widgets/Header/ui/UserPanel.tsx
> +  const [inputValue, setInputValue] = useState('');
вывела в отдельный компонент

2022-11-13 12:40 UTC, malinna13 commented on src/pages/MainPage/index.tsx
> +                  setBoardId(board._id);
поменяла стейт на реф

2022-11-13 13:57 UTC, diXrom approved these changes

2022-11-13 14:17 UTC, merged