Welcome page
diXrom/project-management pull request #16
Opened 2022-11-14 19:34 UTC by vyach-g

Welcome page with anims and i18n. uses index-route

2022-11-14 21:55 UTC, diXrom requested changes

2022-11-14 21:55 UTC, diXrom commented on src/pages/WelcomePage/ui/Functionality.tsx
> +                      variants={tabVariants}
Анимация работает без пропа animate?

2022-11-14 21:55 UTC, diXrom commented on src/pages/WelcomePage/ui/HeroSection.tsx
> +          {/* <Link to="#more">
Доработай якоря [react-scrollchor](https://www.npmjs.com/package/react-scrollchor)

2022-11-14 21:55 UTC, diXrom commented on src/pages/WelcomePage/ui/HeroSection.tsx
> +            <div className="start-btn bg-blue-600 hover:bg-blue-700 transition duration-300 text-white text-lg font-semibold h-14 px-8 rounded-lg w-full flex items-center justify-center sm:w-auto cur
Не вижу откуда start-btn взялся?

2022-11-15 06:54 UTC, vyach-g commented on src/pages/WelcomePage/ui/Functionality.tsx
> +                      variants={tabVariants}
Работала и без animate, но реализовал с

2022-11-15 06:56 UTC, vyach-g commented on src/pages/WelcomePage/ui/HeroSection.tsx
> +          {/* <Link to="#more">
При использовании react-scrollchor ломался роутинг(из-за использования "#" в url), если сначала нажать на кнопку скролла, далее перейти на другую страницу, а потом вернуться на предыдущую. Вместо него использовал react-scroll

2022-11-15 06:56 UTC, vyach-g commented on src/pages/WelcomePage/ui/HeroSection.tsx
> +            <div className="start-btn bg-blue-600 hover:bg-blue-700 transition duration-300 text-white text-lg font-semibold h-14 px-8 rounded-lg w-full flex items-center justify-center sm:w-auto cur
Использовал временные классы для ориентирования в коде во время верстки, убрал все лишние классы

2022-11-15 08:42 UTC, diXrom approved these changes

2022-11-15 08:43 UTC, merged